# Generated by Django 3.2.9 on 2021-11-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='имя тега'),
        ),
    ]
